### ISSUE TITLE
Reducción tamaño de texto de breve info

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/TelartesApp#11]
El texto que aparece en el cuadro rojo habría que reducirlo de tamaño para que se vea mejor. Puede ser el mismo que donde se ve "Plazo límite" con un poco de separación.
Lo mismo para NOTICAS y AGENDA CULTURAL.

![reduccion_texto](https://cloud.githubusercontent.com/assets/7635775/13321699/f18cc930-dba6-11e5-8f59-9ada807252de.jpg)

**Comment by NoemiNahomy** [comment]
Se redujo el texto a "small"
