### ISSUE TITLE
Convocatorias repetidas

### ISSUE THREAD

**Issue by danicotillas** [hacklabcbba/TelartesApp#2]
Seguramente sea por la web pero aparecen convocatorias repetidas.
¿Cómo solucionamos esto?
![convos_repetidas](https://cloud.githubusercontent.com/assets/7635775/13321205/0718ae2a-dba4-11e5-9ba2-f04d6f07960d.jpg)

**Comment by NoemiNahomy** [comment]
Esto lo deben controlar en la web, por otro lado creo qe  es por que son datos de prueba
